events {}

http {

    include /etc/nginx/mime.types;

    server {
        listen 80;

        root /usr/share/nginx/html;

        location /api/ {
            proxy_pass http://localhost:3000/;
        }

        location /acessibilidade-checker/ {
            try_files $uri $uri/ /acessibilidade-checker/index.html;
        }

        location /gerador-plano-aula/ {
            try_files $uri $uri/ /gerador-plano-aula/index.html;
        }

        location /gerador-plano-estudo/ {
            try_files $uri $uri/ /gerador-plano-estudo/index.html;
        }

        location /gerador-questoes-descritivas/ {
            try_files $uri $uri/ /gerador-questoes-descritivas/index.html;
        }

        location /simpatico/ {
            try_files $uri $uri/ /simpatico/index.html;
        }

        location /ajuda-ai/ {
            try_files $uri $uri/ /ajuda-ai/index.html;
        }

        location / {
            try_files $uri $uri/ /site-principal/index.html;
        }
    }
}