events {}

http {

    include /etc/nginx/mime.types;

    server {
        listen 80;

        root /usr/share/nginx/html;

        location /api/ {
            proxy_pass http://localhost:3000/;
        }

        location /ajuda-ai/ {
            try_files $uri $uri/ /ajuda-ai/index.html;
        }

        location /projeto-joao/ {
            try_files $uri $uri/ /projeto-joao/index.html;
        }

        location / {
            try_files $uri $uri/ /site-principal/index.html;
        }
    }
}